### ISSUE TITLE
「N回繰り返す」と四則演算のブロックを組み合わせると、計算の優先順位がおかしい

### ISSUE THREAD

**Issue by nobyuki** [smalruby/smalruby-editor#16]
下記のようなブロックを作ります。

![smalruby-times-bug.png](https://dl.dropboxusercontent.com/s/ymn640tuni7yloj/smalruby-times-bug.png)

このとき、「(10 - 0)」から先に計算することを期待しています。

```ruby
cat1.on(:start) do
  (10 - 0).times do
    move(10)
    await
  end
end
```

しかし、実際には下記のように変換されます。

```ruby
cat1.on(:start) do
  10 - 0.times do
    move(10)
    await
  end
end
```

**Comment by takaokouji** [comment]
#18 にて対応済み
